
name: Testes

# Gatilhos 
# Progamados
# Acionados por Eventos 

on:
  push:
    branches: [ main ]


jobs:
  build:
  
# Maquina ou anbiente
    runs-on: ubuntu-latest
    

   
# Passos
    steps:

# Donwload do codigo
    - uses: actions/checkout@v3
    
# Setup da versão do Node    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14.x
        
    - run: npm install
    - run: npm run cy:run
      continue-on-error: true
    
    - run: npm run report:merge
    
    - run: npm run report:mocha
    
# GitHub Pages --> Publicar os Relatorios 

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4.2.5
      with:
        GITHUB_TOKKEN: ${{ secrets.GITHUB_TOKKEN }}
        BRANCH: gh-pages
        FOLDER: mochawesome-report
    
